# config/packages/security.yaml
security:
    # Hashing de contraseñas
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # Proveedor de usuarios desde la base de datos
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            # Login con formulario
            form_login:
                login_path: app_sign_in          # Ruta del login
                check_path: app_sign_in          # Ruta que procesa login
                enable_csrf: true
                csrf_token_id: authenticate      # Coincide con tu template
                default_target_path: /admin      # Redirección automática después de login
            logout:
                path: app_sign_out
                # Si querés, podés agregar una redirección al logout
                # target: /sign-in

    # Control de acceso
    access_control:
        # Solo usuarios con ROLE_ADMIN pueden entrar a /admin
        - { path: ^/admin, roles: ROLE_ADMIN }

# Configuración específica para test (opcional)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
